# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zw_utils', '0002_auto_20160921_1018'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentScheduleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zw_utils.Currency'),
        ),
        migrations.AddField(
            model_name='repaymentscheduleline',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='scheduled_repayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.RepaymentScheduleLine'),
        ),
    ]
