# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20160921_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='contract_length',
        ),
        migrations.AlterField(
            model_name='loan',
            name='effective_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_interest',
            field=models.DecimalField(decimal_places=2, help_text='Annual interest in %', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='pilot',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
