# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20160921_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='effective_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
