# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20160921_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='number_of_repayments',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
