# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20160929_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repaymentscheduleline',
            old_name='fee_amount',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='repaymentscheduleline',
            old_name='interest_amount',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='repaymentscheduleline',
            old_name='penalty_amount',
            new_name='penalty',
        ),
        migrations.RenameField(
            model_name='repaymentscheduleline',
            old_name='principal_amount',
            new_name='principal',
        ),
    ]
