# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_auto_20161005_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='early_penalty',
            new_name='prepayment_penalty',
        ),
    ]
