# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_auto_20161005_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='late_penalty_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='late_penalty_max_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='late_penalty_per_x_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_interest',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual interest in %', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='number_of_repayments',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='prepayment_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
