# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_auto_20161017_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='number_of_repayments',
            field=models.SmallIntegerField(default=0),
        ),
    ]
