# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_auto_20161017_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_contract_photo',
            field=models.ImageField(blank=True, upload_to='uploads/loan_contract/%Y/%m/%d/'),
        ),
    ]
