# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_auto_20161021_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.LoanPurpose'),
        ),
    ]
