# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_auto_20161023_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
