# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_loan_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='expect_sales_growth',
            field=models.NullBooleanField(default=None),
        ),
    ]
