# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_auto_20161030_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bullet_repayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='normal_repayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='late_penalty_max_days',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='loan',
            name='late_penalty_per_x_days',
            field=models.IntegerField(default=7),
        ),
    ]
