# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 05:26
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0021_auto_20161103_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentscheduleline',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='repaymentscheduleline',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='repaymentscheduleline',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='repaymentscheduleline',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
