# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0024_auto_20161121_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='contract_due_date',
        ),
    ]
