# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_auto_20161208_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='repaid_on',
            field=models.DateField(blank=True, help_text='Automatically set to the date of the repayment closing the loan. Not set for open loans.', null=True),
        ),
    ]
