# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0028_auto_20161220_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='contract_number',
            field=models.CharField(blank=True, default=loans.models.Loan.generate_contract_number, max_length=50),
        ),
    ]
