# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0029_auto_20170104_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='borrowers.Borrower'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans_guaranteed', to='borrowers.Borrower'),
        ),
    ]
