# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from datetime import timedelta


def default_timestamp():
    return django.utils.timezone.now() + timedelta(days=-7000)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0030_auto_20170115_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='repayment',
            name='recorded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='uploaded_at',
            # for past records, set a timestamp in the 90s
            field=models.DateTimeField(auto_now_add=True, default=default_timestamp),
            preserve_default=False,
        ),
    ]
