# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0031_auto_20170210_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonForDelayedRepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_en', models.CharField(blank=True, max_length=50)),
                ('reason_mm', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
