# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0033_repayment_reason_for_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.SmallIntegerField(choices=[(101, 'Draft request'), (102, 'Request submitted'), (103, 'Request rejected'), (104, 'Request approved'), (105, 'Request signed by borrower'), (106, 'Loan disbursed'), (107, 'Loan fully repaid'), (201, 'Loan defaulted'), (301, 'Fraud suspected'), (302, 'Fraud confirmed')], default=101),
        ),
    ]
