# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 12:37
from __future__ import unicode_literals

from django.db import migrations
import django_fsm
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0035_remove_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='state',
            field=django_fsm.FSMField(choices=[(loans.models.LoanState(101), 'Draft request'), (loans.models.LoanState(102), 'Request submitted'), (loans.models.LoanState(103), 'Request rejected'), (loans.models.LoanState(104), 'Request approved'), (loans.models.LoanState(105), 'Request signed by borrower'), (loans.models.LoanState(106), 'Loan disbursed'), (loans.models.LoanState(107), 'Loan fully repaid'), (loans.models.LoanState(201), 'Loan defaulted'), (loans.models.LoanState(301), 'Fraud suspected'), (loans.models.LoanState(302), 'Fraud confirmed')], default=loans.models.LoanState(101), max_length=50),
        ),
    ]
