# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0037_auto_20170305_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequestReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('alternative_offer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='loans.Loan')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='loans.Loan')),
                ('reviewer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_state', models.SmallIntegerField(choices=[(loans.models.LoanState(101), 'Draft request'), (loans.models.LoanState(102), 'Request submitted'), (loans.models.LoanState(103), 'Request rejected'), (loans.models.LoanState(104), 'Request approved'), (loans.models.LoanState(105), 'Request signed by borrower'), (loans.models.LoanState(106), 'Loan disbursed'), (loans.models.LoanState(107), 'Loan fully repaid'), (loans.models.LoanState(201), 'Loan defaulted'), (loans.models.LoanState(301), 'Fraud suspected'), (loans.models.LoanState(302), 'Fraud confirmed')])),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
        ),
    ]
