# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0038_loanrequestreview_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBorrowerSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSignature',
            fields=[
                ('baseborrowersignature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loans.BaseBorrowerSignature')),
                ('photo', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToUUID(path='loan_signatures'))),
            ],
            bases=('loans.baseborrowersignature',),
        ),
        migrations.AddField(
            model_name='baseborrowersignature',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='loans.Loan'),
        ),
    ]
