# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0040_photosignature_api_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.Loan'),
        ),
    ]
