# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0041_auto_20170316_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft request'), ('submitted', 'Request submitted'), ('rejected', 'Request rejected'), ('approved', 'Request approved'), ('signed', 'Request signed by borrower'), ('disbursed', 'Loan disbursed'), ('repaid', 'Loan fully repaid'), ('defaulted', 'Loan defaulted'), ('LOAN_FRAUD_suspected', 'Fraud suspected'), ('LOAN_FRAUD_confirmed', 'Fraud confirmed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='new_state',
            field=models.CharField(choices=[('draft', 'Draft request'), ('submitted', 'Request submitted'), ('rejected', 'Request rejected'), ('approved', 'Request approved'), ('signed', 'Request signed by borrower'), ('disbursed', 'Loan disbursed'), ('repaid', 'Loan fully repaid'), ('defaulted', 'Loan defaulted'), ('LOAN_FRAUD_suspected', 'Fraud suspected'), ('LOAN_FRAUD_confirmed', 'Fraud confirmed')], max_length=50),
        ),
    ]
