# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0042_auto_20170316_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='reason_for_delay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loans.ReasonForDelayedRepayment'),
        ),
    ]
