# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 07:54
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0043_repayment_reconcile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repayment',
            name='reconcile_status',
        ),
        migrations.AddField(
            model_name='repayment',
            name='reconciliation_status',
            field=django_fsm.FSMField(choices=[('not reconciled', 'not reconciled'), ('reconciled', 'reconciled'), ('need manual reconciliation', 'need manual reconciliation')], default='not reconciled', max_length=50),
        ),
    ]
