# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 07:37
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0044_auto_20170502_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='reconciliation_status',
            field=django_fsm.FSMField(choices=[('not reconciled', 'not reconciled'), ('auto reconciled', 'auto reconciled'), ('manual reconciled', 'manual reconciled'), ('need manual', 'need manual reconciliation')], default='not reconciled', max_length=50),
        ),
    ]
