# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 08:10
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import migrations


def create_bot(apps, schema_editor):
    #User = apps.get_model('auth', 'User')
    bot_user = User.objects.create_user(username='reconciliation_bot', password='hello')
    bot_user.set_unusable_password()
    bot_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0045_auto_20170509_1407'),
        ('zw_utils', '0004_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_bot)
    ]
