# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0046_auto_20170512_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reconciled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='repayment',
            name='reconciliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Reconciliation'),
        ),
    ]
