# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 09:37
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0047_auto_20170512_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='reconciliation_status',
            field=django_fsm.FSMField(choices=[('not reconciled', 'not reconciled'), ('auto reconciled', 'auto reconciled'), ('manual reconciled', 'manual reconciled'), ('need manual reconciliation', 'need manual reconciliation')], default='not reconciled', max_length=50),
        ),
    ]
