# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0048_auto_20170512_1607'),
        ('loans', '0043_auto_20170512_1236'),
    ]

    operations = [
    ]
