# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 02:56
from __future__ import unicode_literals

from datetime import date
from django.db import migrations
from loans.models import LOAN_DISBURSED, LOAN_REPAID, LOAN_REQUEST_DRAFT, LOAN_REQUEST_SUBMITTED


def set_loans_states(apps, schema_editor):
    Loan = apps.get_model('loans', 'Loan')

    # set repaid loans to LOAN_REPAID
    Loan.objects.filter(repaid_on__isnull=False).update(state=LOAN_REPAID)

    # loans contracted in the past are probably disbursed by now
    Loan.objects.filter(
        repaid_on__isnull=True
    ).filter(
        contract_date__lt=date.today()
    ).update(
        state=LOAN_DISBURSED
    )

    # set remaining drafts to SUBMITTED
    Loan.objects.filter(state=LOAN_REQUEST_DRAFT).update(state=LOAN_REQUEST_SUBMITTED)


class Migration(migrations.Migration):
    # set state to sensible values for existing loans
    # this is a one off data migration, not meant to be reused

    dependencies = [
        ('loans', '0050_auto_20170516_1057'),
    ]

    operations = [
        migrations.RunPython(set_loans_states),
    ]
