# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 04:25
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0052_auto_20170523_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_interest_type',
            field=django_fsm.FSMField(choices=[('declining balance - actual / 360', 'declining balance - actual / 360'), ('declining balance - actual / 365', 'declining balance - actual / 365'), ('declining balance - equal repayments', 'declining balance - equal repayments')], default='declining balance - actual / 360', max_length=50),
        ),
    ]
