# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0053_auto_20170526_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_interest_days',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_interest_duration',
            field=django_fsm.FSMField(choices=[('monthly interest', 'monthly interest'), ('yearly interest', 'yearly interest')], default='monthly interest', max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text=' % interest per monthly or yearly ', max_digits=12),
        ),
    ]
