# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 08:12
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0054_auto_20170531_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_interest_type',
            field=django_fsm.FSMField(choices=[('actual_360', 'actual_360'), ('actual_365', 'actual_365'), ('equal_repayments', 'equal_repayments')], default='actual_360', max_length=50),
        ),
    ]
