# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0055_auto_20170608_1442'),
        ('loans', '0051_auto_20170612_0256'),
    ]

    operations = [
    ]
