# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 13:10
from __future__ import unicode_literals

from django.db import migrations
from loans.models import ACTUAL_360


def set_loan_interest_types(apps, schema_editor):
    Loan = apps.get_model('loans', 'Loan')

    Loan.objects.all().update(loan_interest_type=ACTUAL_360)


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0056_merge_20170617_0927'),
    ]

    operations = [
        migrations.RunPython(set_loan_interest_types),
    ]
