# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def set_uploaded_at_to_contract_date(apps, schema_editor):
    Loan = apps.get_model('loans', 'Loan')

    for loan in Loan.objects.all():
        loan.uploaded_at = loan.contract_date
        loan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0057_auto_20170618_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_uploaded_at_to_contract_date),
    ]
