# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 13:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0015_agent_last_money_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0058_loan_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.IntegerField(choices=[(1, 'Cash at agent'), (2, 'KBZ Bank over the counter transfer'), (3, 'Wave Peer-to-Peer transfer')], default=1)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('state', django_fsm.FSMField(choices=[('requested', 'Disbursement requested'), ('sent', 'Money disbursed'), ('cancelled', 'Disbursement cancelled')], default='requested', max_length=50)),
                ('disbursed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disbursed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='CashAtAgentDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('loans.disbursement',),
        ),
        migrations.CreateModel(
            name='KBZGenericDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('loans.disbursement',),
        ),
        migrations.CreateModel(
            name='WaveP2PDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('loans.disbursement',),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans_disbursed', to='loans.Disbursement'),
        ),
    ]
