# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0060_auto_20170625_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the agent saved the repayment in the app'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the app uploaded this to the server'),
        ),
    ]
