# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0061_auto_20170725_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loans.Reconciliation'),
        ),
    ]
