# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 14:33
from __future__ import unicode_literals
from django.core import management
from django.db import migrations


def createinitialrevisions(apps, schema_editor):
    management.call_command('createinitialrevisions')


class Migration(migrations.Migration):
    dependencies = [
        ('loans', '0062_auto_20170817_0940'),
        # ('reversion', '0004_auto_20160611_1202'),
        # FIXME: Strangely, issue 206 is not working well without this dependency. Maybe this can be removed later.
        # ('borrowers', '0018_auto_20170727_0803'),
    ]

    operations = [
        # migrations.RunPython(createinitialrevisions),
    ]
