# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 09:26
from __future__ import unicode_literals

from django.core import management
from django.db import migrations


def createinitialrevisions(apps, schema_editor):
    management.call_command('createinitialrevisions', 'loans.Loan')
    management.call_command('createinitialrevisions', 'loans.RepaymentScheduleLine')


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0063_createinitialrevs_repayments'),
    ]

    operations = [
        # migrations.RunPython(createinitialrevisions),
    ]
