# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transfer'),
        ('loans', '0065_superusertolenderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.Transfer'),
        ),
    ]
