# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0066_disbursement_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='superusertolenderpayment',
            name='loans',
            field=models.ManyToManyField(to='loans.Loan'),
        ),
    ]
