# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0067_superusertolenderpayment_loans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': (('zw_request_loan', 'Can request a new loan'), ('zw_approve_loan', 'Can approve a loan request'), ('zw_disburse_loan', 'Can disburse a loan'))},
        ),
    ]
