# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0069_repayment_superuser_to_lender_payment'),
        ('loans', '0068_auto_20180704_1350'),
    ]

    operations = [
    ]
