# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0070_merge_20180720_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='superusertolenderpayment',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loans.Reconciliation'),
        ),
        migrations.AddField(
            model_name='superusertolenderpayment',
            name='reconciliation_status',
            field=django_fsm.FSMField(choices=[('not reconciled', 'not reconciled'), ('auto reconciled', 'auto reconciled'), ('manual reconciled', 'manual reconciled'), ('need manual reconciliation', 'need manual reconciliation')], default='not reconciled', max_length=50),
        ),
    ]
