# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-23 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0070_merge_20180720_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superusertolenderpayment',
            name='loans',
            field=models.ManyToManyField(blank=True, to='loans.Loan'),
        ),
    ]
