# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-20 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0071_auto_20181015_1426'),
        ('loans', '0071_auto_20181023_1155'),
    ]

    operations = [
    ]
