# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-18 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0072_merge_20181120_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashAtAgentDisbursement',
        ),
        migrations.DeleteModel(
            name='KBZGenericDisbursement',
        ),
        migrations.DeleteModel(
            name='WaveP2PDisbursement',
        ),
        migrations.CreateModel(
            name='BankTransferDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('loans.disbursement',),
        ),
        migrations.CreateModel(
            name='WaveTransferAndCashOutDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('loans.disbursement',),
        ),
        migrations.CreateModel(
            name='WaveTransferDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('loans.disbursement',),
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='disbursed_by',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='transfer',
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='method',
            field=models.IntegerField(choices=[(1, 'Wave transfer'), (2, 'Bank transfer'), (3, 'Wave Transfer and Cash Out')], default=1),
        ),
    ]
