# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-12 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0075_auto_20190123_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('will_default', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_prediction', to='loans.Loan')),
            ],
        ),
    ]
