# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0075_auto_20190123_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repaymentscheduleline',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
