# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-18 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0076_auto_20191015_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repayment_list', to='loans.Reconciliation'),
        ),
    ]
