# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0077_auto_20191018_0541'),
        ('loans', '0076_defaultprediction'),
    ]

    operations = [
    ]
