# Generated by Django 2.2 on 2020-05-19 07:55

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0078_merge_20200303_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='details',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_disbursed', to='loans.Disbursement'),
        ),
        migrations.AlterField(
            model_name='photosignature',
            name='api_result',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
