# Generated by Django 2.2 on 2020-06-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0079_auto_20200519_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultprediction',
            old_name='will_default',
            new_name='passed_credit',
        ),
    ]
